# German word list for onionname suggestions (romanized ASCII)
# Format: adjective-noun (e.g., "frohlich-adler")
# People: only those born before 1900, no political/religious figures

ADJECTIVES = [
    "achtsam", "aktiv", "anmutig", "aufrecht", "aufrichtig",
    "beherzt", "besonnen", "brav", "brillant",
    "edel", "eifrig", "elegant", "emsig", "ernst",
    "fein", "fest", "flink", "flott", "freimutig", "freudig",
    "friedlich", "frisch", "frohlich", "furchtlos",
    "galant", "gerecht", "geschickt", "gewandt", "golden", "grossmutig",
    "gutmutig",
    "heiter", "hell", "herzlich", "hilfreich", "hoffnungsvoll",
    "ideal", "innig",
    "jovial", "jugendlich",
    "klar", "klug", "kostbar", "kraftig", "kreativ", "kuhn",
    "lauter", "lebhaft", "leicht", "leuchtend", "liebevoll", "lustig",
    "magisch", "majestätisch", "mild", "munter", "mutig",
    "nett", "nobel",
    "offen", "optimal",
    "pfiffig", "prachtig",
    "rasch", "redlich", "rein", "reizend", "robust", "ruhig",
    "sanft", "scharfsinnig", "schlau", "sicher", "sonnig", "stabil",
    "standhaft", "stark", "stetig", "stolz", "strahlend",
    "tapfer", "tatkraftig", "treu", "tuchtig",
    "umsichtig", "unerschrocken",
    "verlasslich", "vital", "vornehm",
    "wach", "wacker", "warm", "weise", "wert", "wichtig", "witzig",
    "wunderbar",
    "zart", "zufrieden", "zuversichtlich",
]

NOUNS = [
    # Animals
    "adler", "amsel",
    "bar", "biber", "biene", "buchfink",
    "dachs", "delphin", "drossel",
    "eichhorn", "eisvogel", "elch", "eule",
    "falke", "flamingo", "forelle", "fuchs",
    "gans", "gazelle", "gemse",
    "habicht", "hamster", "hase", "hirsch",
    "igel",
    "jaguar",
    "kaninchen", "kolibri", "kondor", "kranich",
    "lachs", "lerche", "leopard", "libelle", "lowe", "luchs",
    "marder", "meise", "murmeltier",
    "nachtigall", "narwal",
    "otter",
    "papagei", "pelikan", "pfau", "pinguin",
    "rabe", "reiher", "rotkehlchen",
    "schmetterling", "schwan", "seehund", "sperling", "storch",
    "taube", "tiger",
    "uhu",
    "wal", "wolf",
    "zebra",

    # Nature
    "ahorn", "amber", "amethyst",
    "basalt", "berg", "birke", "blitz", "buche",
    "donner", "dune",
    "eiche", "eis", "erle",
    "felsen", "fjord", "flamme", "fluss", "forst", "frost",
    "gipfel", "gletscher", "granit",
    "hafen", "heide", "horizont", "hugel",
    "insel",
    "jade", "jasmin",
    "kiesel", "klippe", "kristall", "kupfer",
    "linde", "lotos",
    "marmor", "mond", "moos",
    "nebel", "norden",
    "oase", "opal", "orchidee",
    "palme", "perle", "pinie",
    "quarz", "quelle",
    "regen", "rose", "rubin",
    "saphir", "schnee", "silber", "sonne", "stern", "strom",
    "tal", "tanne", "topas",
    "vulkan",
    "walde", "weide", "wiese", "wind",
    "zeder", "zephyr",

    # Objects
    "amboss", "anker", "atlas",
    "banner", "bogen", "burg",
    "dolch", "dorn",
    "fackel", "feder", "festung", "flote",
    "glocke", "globus",
    "harfe", "helm", "horn",
    "kamin", "kette", "kompass", "krone",
    "laterne", "leuchtturm",
    "mosaik", "muhle",
    "nadel", "nest",
    "orakel",
    "palast", "pergament", "pfeiler", "portal",
    "ratsel", "rune",
    "schild", "schmiede", "schwert", "spiegel", "spindel",
    "tempel", "turm",
    "uhr",
    "wappen", "werkstatt",

    # Authors / artists / thinkers (born before 1900)
    "bach", "beethoven", "brahms",
    "durer",
    "gauss", "goethe", "grimm", "gutenberg",
    "handel", "haydn", "hegel", "heine", "humboldt",
    "kafka", "kant", "kepler", "klimt",
    "leibniz", "liszt",
    "mahler", "mendelssohn", "mozart",
    "nietzsche",
    "planck",
    "rilke",
    "schiller", "schubert", "schumann", "strauss",
    "wagner", "weber",
]
