# English word list for onionname suggestions
# Format: adjective-noun (e.g., "cheerful-penguin")
# All words ASCII lowercase
# Rules: no depressing/negative adjectives, no insult-animals, no religious
# or political figures, no firearms. Old weapons (medieval) OK.
# People: only those born before 1900, known for cultural/intellectual work.

ADJECTIVES = [
    "able", "agile", "alert", "alive", "amazing", "ample", "ancient",
    "ardent", "artful", "astute", "august", "avid", "aware",
    "balanced", "beloved", "benign", "blessed", "blissful", "bold",
    "bonny", "brainy", "brave", "breezy", "bright", "brisk",
    "bubbly", "bustling",
    "calm", "candid", "capable", "careful", "caring", "central",
    "charming", "cheerful", "chosen", "civic", "civil", "classic",
    "clean", "clear", "clever", "close", "coastal", "cozy",
    "crafty", "creative", "crisp", "curious",
    "dainty", "dapper", "daring", "dear", "decent", "deep",
    "deft", "devoted", "diligent", "distinct", "divine", "dreamy",
    "driven", "durable", "dynamic",
    "eager", "early", "earnest", "earthy", "eastern", "easy",
    "elegant", "elite", "endless", "epic", "equal", "even",
    "evident", "exact", "expert",
    "fabled", "factual", "fair", "faithful", "familiar", "famous",
    "fancy", "fearless", "fertile", "festive", "fierce", "fine",
    "firm", "fleet", "flowing", "fluent", "flying", "focal",
    "fond", "forged", "formal", "frank", "free",
    "fresh", "friendly", "frugal", "fruitful", "fun", "funny",
    "gallant", "gathered", "gentle", "genuine", "gifted",
    "glad", "gleaming", "global", "glowing", "golden", "good",
    "graceful", "grand", "grateful", "great", "green", "growing",
    "guided",
    "handy", "happy", "hardy", "harmless", "healing",
    "hearty", "helpful", "hidden", "honest", "hopeful", "humble",
    "ideal", "immense", "infinite", "inland",
    "inner", "inspired", "inviting", "iron",
    "jazzy", "jolly", "jovial", "joyful", "joyous",
    "jubilant", "just",
    "keen", "kind", "kindred", "knowing",
    "lasting", "lavish", "leading", "learned",
    "level", "light", "likely", "lively", "local",
    "lofty", "logical", "loving", "loyal", "lucid",
    "lucky", "lunar", "lyrical",
    "magic", "main", "major", "marble", "marine",
    "mellow", "merry", "mighty", "mild",
    "mindful", "mirthful", "mobile", "modern", "modest",
    "moral", "moving", "musical", "mutual",
    "native", "natural", "naval", "neat", "neutral",
    "nimble", "noble", "noted", "novel", "nurturing",
    "oaken", "oceanic", "onward", "open",
    "optimal", "orange", "orderly", "organic", "outer",
    "pacific", "patient", "peaceful", "peerless", "peppy", "perky",
    "placid", "plain", "playful", "pleasant", "plucky", "poetic",
    "polite", "popular", "potent", "precise", "prime", "prized",
    "prompt", "proper", "proud", "prudent", "pure",
    "quaint", "quality", "quick", "quiet", "quirky",
    "radiant", "rapid", "rare", "ready", "regal", "relaxed",
    "remote", "resilient", "rich", "right", "rising", "robust",
    "rosy", "round", "royal", "rugged", "rural", "rustic",
    "sacred", "safe", "sage", "satin", "savvy", "scenic",
    "secure", "serene", "settled", "sharp", "shining",
    "silent", "silken", "silver", "simple", "sincere", "skilled",
    "sleek", "slender", "smart", "smooth", "snowy", "social",
    "soft", "solar", "solid", "sonic", "sound", "southern",
    "special", "speedy", "spirited", "splendid", "stable",
    "stately", "steady", "stellar", "stoic", "stout", "strong",
    "sturdy", "subtle", "sunny", "superb", "supple",
    "sure", "sweet", "swift",
    "tactful", "tawny", "tender", "thankful", "thorough",
    "tidy", "timely", "tireless", "total",
    "tranquil", "trim", "tropical", "true",
    "trusted", "truthful", "tuned", "turquoise",
    "unified", "unique", "united",
    "upbeat", "upright", "urban", "useful",
    "valiant", "valid", "valued", "varied", "vast", "velvet",
    "vibrant", "vigilant", "vintage", "violet",
    "visible", "vital", "vivid", "vocal",
    "warm", "watchful", "welcome", "western", "whole", "wide",
    "willing", "winding", "winged", "winning",
    "wise", "witty", "wonderful", "worthy",
    "young",
    "zealous", "zesty",
]

NOUNS = [
    # Animals (no insult-animals: removed snake, weasel, monkey, hyena,
    # vulture, viper, wasp)
    "albatross", "alpaca", "antelope", "badger", "barracuda", "bat",
    "bear", "beaver", "beetle", "bison", "bluebird", "bobcat",
    "buffalo", "butterfly", "camel", "canary", "cardinal", "caribou",
    "catfish", "chameleon", "cheetah", "cicada", "condor",
    "coral", "corgi", "cormorant", "cougar", "coyote", "crane",
    "cricket", "crow", "cuckoo", "curlew",
    "darter", "deer", "dingo", "dolphin", "donkey", "dove",
    "dragonfly", "duck", "dugong",
    "eagle", "egret", "elephant", "elk", "emu", "ermine",
    "falcon", "ferret", "finch", "firefly", "flamingo", "flounder",
    "fox", "frog", "gannet", "gazelle", "gecko", "gerbil",
    "giraffe", "goat", "goldfinch", "goose", "gorilla", "grouse",
    "gryphon", "gull",
    "hamster", "hare", "hawk", "hedgehog", "heron", "hound",
    "hummingbird",
    "ibis", "iguana", "impala",
    "jackal", "jackdaw", "jaguar", "jay", "jellyfish",
    "kangaroo", "kestrel", "kingfisher", "kite", "kiwi", "koala",
    "kookaburra",
    "ladybug", "lark", "lemming", "lemur", "leopard", "lion",
    "lizard", "llama", "lobster", "locust", "loon", "lynx",
    "macaw", "magpie", "mallard", "mammoth", "manatee", "manta",
    "mantis", "marmot", "marten", "meadowlark", "meerkat",
    "mink", "minnow", "mockingbird", "mongoose", "moose",
    "moth", "mouse", "mule", "muskrat",
    "narwhal", "newt", "nighthawk", "nightjar",
    "ocelot", "octopus", "okapi", "opossum", "orca", "oriole",
    "osprey", "ostrich", "otter", "owl", "oyster",
    "panda", "panther", "parrot", "partridge", "peacock", "pelican",
    "penguin", "pheasant", "pigeon", "pika", "platypus", "plover",
    "pony", "porcupine", "porpoise", "possum", "puffin",
    "python",
    "quail", "quetzal", "quokka",
    "rabbit", "raccoon", "raven", "reindeer", "rhino", "roadrunner",
    "robin", "rooster", "rook",
    "sailfish", "salamander", "salmon", "sandpiper", "sardine",
    "seahorse", "seal", "shark", "shrike", "skylark",
    "sloth", "snail", "snipe", "sparrow", "spider",
    "squid", "squirrel", "stallion", "starfish", "starling",
    "stingray", "stork", "sturgeon", "sunbird", "swallow", "swan",
    "tapir", "tarpon", "tern", "thrush", "tiger", "toad",
    "tortoise", "toucan", "trout", "tuna", "turkey", "turtle",
    "unicorn",
    "wallaby", "walrus", "warbler", "warthog",
    "whale", "wildcat", "wolf", "wolverine", "wombat", "woodpecker",
    "wren",
    "yak",
    "zebra",

    # Nature / geography
    "acacia", "acorn", "agate", "amber", "amethyst", "anchor",
    "arbor", "arctic", "aspen", "atoll", "aurora", "avalanche",
    "bamboo", "basalt", "basin", "bay", "beach", "beacon",
    "birch", "blaze", "bloom", "blossom", "bluff", "boulder",
    "breeze", "bridge", "brook", "butte",
    "cairn", "canyon", "cape", "cascade", "cave", "cedar",
    "channel", "cherry", "chestnut", "cliff", "cloud", "clover",
    "coast", "cobalt", "copper", "cosmos", "cove", "crater",
    "creek", "crest", "crystal", "current", "cypress",
    "dahlia", "dale", "delta", "desert", "dewdrop", "dune",
    "echo", "eclipse", "elm", "ember", "emerald", "equinox",
    "estuary",
    "fern", "field", "fjord", "flame", "flint", "flora",
    "forest", "fountain", "frost", "fuchsia",
    "galaxy", "garden", "garnet", "glacier", "glade", "glen",
    "gorge", "granite", "grove", "gust",
    "harbor", "hazel", "heath", "heather", "hemlock", "hickory",
    "highland", "hill", "hollow", "horizon", "hyacinth",
    "iceberg", "inlet", "iris", "island", "ivy",
    "jade", "jasmine", "jasper", "juniper",
    "kelp", "knoll",
    "lagoon", "lake", "lantern", "larch", "laurel", "lava",
    "leaf", "ledge", "lightning", "lilac", "lily", "linden",
    "lotus",
    "magnolia", "mahogany", "mangrove", "maple", "marsh", "meadow",
    "mesa", "meteor", "mica", "midnight", "mist", "monsoon",
    "moon", "moorland", "moss", "mountain", "mulberry",
    "nebula", "nectar", "nettle", "north", "nova", "nutmeg",
    "oak", "oasis", "obsidian", "ocean", "onyx",
    "opal", "orbit", "orchid",
    "palm", "pebble", "peony", "petal", "pine", "pinnacle",
    "planet", "plateau", "plum", "pond", "poplar",
    "poppy", "prairie", "prism", "pulse",
    "quartz", "quasar",
    "rain", "rainbow", "rapids", "ravine", "reef", "ridge",
    "ripple", "river", "rose", "rowan", "ruby", "rush",
    "saffron", "sage", "sand", "sapphire", "savanna", "sequoia",
    "shore", "sierra", "sky", "slate", "snow", "solstice",
    "south", "spring", "spruce", "star", "starlight", "stone",
    "storm", "stream", "summit", "sunrise", "sunset", "surf",
    "sycamore",
    "teak", "tempest", "thistle", "thorn", "thunder", "tide",
    "timber", "topaz", "torrent", "trail", "tulip", "tundra",
    "twilight",
    "vale", "valley", "vine", "violet",
    "volcano", "vortex",
    "waterfall", "wave", "west", "willow", "wind", "winter",
    "wisteria", "woodland",
    "yarrow", "yew",
    "zenith", "zephyr", "zinc", "zinnia",

    # Objects / concepts (medieval weapons OK, no firearms)
    "anvil", "archive", "arrow", "atlas", "axle",
    "banner", "barrel", "bastion", "bell", "blade", "blanket",
    "bolt", "bonfire", "book", "bower", "bracer", "brass",
    "brick", "buckle", "bugle",
    "cabin", "cable", "candle", "canvas", "cargo", "castle",
    "chalice", "chapel", "charm", "chimney", "cipher", "circuit",
    "citadel", "clarion", "clasp", "clock", "cobble", "coil",
    "column", "compass", "conduit", "corner", "cottage",
    "cradle", "crown", "crucible",
    "dagger", "depot", "dial", "dock", "dome", "doorway",
    "drum", "dynamo",
    "emblem", "engine", "envoy", "epoch", "essence",
    "fabric", "fable", "feather", "fiddle", "flagon", "flask",
    "flute", "forge", "fort", "frame", "furnace",
    "gallery", "garland", "gauntlet", "gazette", "gear", "girder",
    "globe", "glyph", "goblet", "guild",
    "hammer", "harp", "haven", "hearth", "helm", "herald",
    "hinge", "horn", "hourglass",
    "icon", "inkwell", "insignia",
    "javelin", "jewel", "journal", "junction",
    "kayak", "keep", "kernel", "kettle", "keystone", "kiln",
    "knapsack", "knight", "knot",
    "labyrinth", "ladder", "lance", "lanyard", "latch", "lattice",
    "ledger", "lens", "lever", "library", "lighthouse", "locket",
    "lodge", "loom", "lute",
    "mallet", "manor", "mantle", "market", "mast", "matrix",
    "medal", "memoir", "mentor", "mill", "mirror", "mission",
    "moat", "monument", "mortar", "mosaic", "motto", "mural",
    "needle", "nest", "nexus", "nimbus", "notion",
    "oracle", "outpost",
    "paddle", "pageant", "palace", "pallet", "parcel", "parish",
    "parlor", "parapet", "path", "patron", "pavilion", "pendant",
    "pennant", "perch", "pharos", "pier", "pillar", "pivot",
    "plank", "plaza", "pledge", "plinth", "portal", "post",
    "press", "pulley", "puzzle",
    "quarry", "quay", "quill", "quiver",
    "rampart", "realm", "relic", "remedy", "riddle", "rigging",
    "ring", "rune",
    "saddle", "saga", "satchel", "scaffold", "scroll", "sentry",
    "shard", "shelter", "shield", "shrine", "signal", "signet",
    "silo", "sketch", "smithy", "socket", "sonnet", "spade",
    "spanner", "spark", "spear", "spindle", "spire", "spoke",
    "spur", "staff", "stage", "stake", "standard", "staple",
    "steeple", "stirrup", "stockade", "strand",
    "studio", "sundial", "symbol",
    "tablet", "talisman", "tapestry", "temple",
    "terrace", "thread", "throne", "tinker", "token",
    "tome", "torch", "totem", "tower", "trident", "trinket",
    "tripod", "trophy", "trumpet", "trunk", "turret",
    "umbrella",
    "valve", "vanguard", "vault", "vessel", "viaduct",
    "vigil",
    "wagon", "warden", "warrant", "watch", "wedge", "wheel",
    "whistle", "windmill", "winch", "workshop", "wreath",
    "zipper",

    # Fictional characters (mythology, literature, folklore —
    # no tragic/dark: removed hamlet, macbeth, faust)
    "achilles", "aladdin", "aragorn", "ariel",
    "baggins", "bilbo",
    "calypso", "cassandra", "circe",
    "daedalus", "dulcinea",
    "elrond", "excalibur",
    "figaro", "frodo",
    "galahad", "gandalf", "gatsby", "gawain", "gulliver",
    "hercules", "hobbit",
    "icarus",
    "juliet",
    "lancelot", "legolas",
    "merlin", "mulan",
    "nemo",
    "oberon", "odysseus", "ophelia", "orlando", "orpheus",
    "pandora", "parsifal", "percival", "phoenix",
    "prospero",
    "quixote",
    "rapunzel", "romeo", "rosalind",
    "samwise", "scheherazade", "sherlock", "sinbad",
    "tarzan", "titan", "tristan",
    "ulysses",
    "valkyrie",
    "watson", "wizard",
    "zorro",

    # Authors / writers (born before 1900, no political figures)
    "austen",
    "balzac", "borges", "bronte", "byron",
    "cervantes", "chekhov", "colette",
    "dante", "defoe", "dickens", "dumas",
    "eliot", "emerson",
    "flaubert",
    "goethe",
    "hardy", "hawthorne", "homer", "hugo",
    "ibsen",
    "joyce",
    "kafka", "keats", "kipling",
    "melville", "moliere",
    "nabokov", "neruda",
    "ovid",
    "poe", "proust", "pushkin",
    "rilke", "rumi",
    "sappho", "shelley", "swift",
    "tagore", "thoreau", "tolkien", "tolstoy", "twain",
    "verne", "virgil", "voltaire",
    "whitman", "wilde", "woolf",
    "yeats",
    "zola",

    # Artists / musicians (born before 1900, no religious/political)
    "bach", "beethoven", "bernini", "bosch", "brahms",
    "caravaggio", "cezanne", "chopin",
    "degas", "dvorak",
    "gaudi", "gauguin", "giotto", "goya",
    "handel", "haydn", "hokusai",
    "klimt",
    "liszt",
    "matisse", "mendelssohn", "monet", "mozart", "mucha", "munch",
    "paganini",
    "rachmaninoff", "raphael", "rembrandt", "renoir", "rodin",
    "satie", "schubert", "sibelius", "strauss", "stravinsky",
    "tchaikovsky", "titian", "turner",
    "uccello",
    "vermeer", "vivaldi",

    # Scientists / thinkers (born before 1900, no political)
    "archimedes", "aristotle",
    "babbage",
    "copernicus", "curie",
    "darwin",
    "euclid", "euler",
    "faraday", "fibonacci",
    "galileo", "gauss",
    "halley", "hypatia",
    "kepler",
    "laplace", "leibniz", "lovelace",
    "maxwell", "mendel",
    "newton", "nightingale", "nobel",
    "pascal", "pasteur", "ptolemy", "pythagoras",
    "ramanujan",
    "socrates",
    "tesla",
    "volta",
]
