# Spanish word list for onionname suggestions (romanized ASCII)
# Format: adjective-noun (e.g., "alegre-condor")
# People: only those born before 1900, no political/religious figures

ADJECTIVES = [
    "activo", "afable", "agil", "alegre", "amable", "amplio",
    "antiguo", "ardiente", "astuto", "atento", "audaz",
    "bello", "bondadoso", "bravo", "brillante", "bueno",
    "calido", "calmo", "capaz", "celeste", "certero", "claro",
    "cordial", "cortés", "creativo", "curioso",
    "decente", "diestro", "digno", "discreto", "dulce", "duradero",
    "eficaz", "elegante", "encantado", "entero", "eterno",
    "fabuloso", "fecundo", "fertil", "festivo", "fiel", "fino",
    "firme", "fluido", "formal", "franco", "fresco", "fuerte",
    "galante", "generoso", "gentil", "glorioso", "gracioso",
    "grande", "grato",
    "habil", "honesto", "humilde",
    "ideal", "ilustre", "inmenso", "ingenioso",
    "jovial", "justo", "juvenil",
    "leal", "libre", "ligero", "limpio", "lucido", "luminoso",
    "magico", "manso", "mayor", "modesto", "moral", "musical",
    "natural", "noble", "notable", "nuevo",
    "optimo", "ordenado",
    "pacifico", "pleno", "preciso", "profundo", "prudente", "puro",
    "querido", "quieto",
    "radioso", "rapido", "raro", "real", "resuelto", "rico",
    "robusto", "rustico",
    "sabio", "sagrado", "sereno", "simple", "sincero", "solar",
    "solido", "sublime", "suave", "sutil",
    "tenaz", "tierno", "total", "tranquilo", "tropical",
    "unico", "util",
    "valiente", "valioso", "vasto", "veloz", "vibrante", "vivo",
    "zeloso",
]

NOUNS = [
    # Animals
    "aguila", "albatros", "alpaca", "antilope",
    "ballena", "bisonte", "buho", "bufalo",
    "caballo", "camello", "canario", "caribu", "castor", "ciervo",
    "cigarra", "cisne", "colibri", "condor", "conejo", "coyote",
    "delfin",
    "elefante", "escarabajo", "estrella",
    "falcon", "flamingo", "foca",
    "gaviota", "gacela", "gorila", "grulla",
    "halcon",
    "iguana",
    "jaguar",
    "koala",
    "lagarto", "leon", "leopardo", "liebre", "llama", "lobo",
    "loro", "lince",
    "mariposa", "nutria",
    "orca", "oso",
    "paloma", "panda", "pantera", "pelicano", "perdiz", "pinguino",
    "puma",
    "quetzal",
    "raton", "ruisenor",
    "salmon", "tigre", "tortuga", "trucha", "tucan",
    "venado",
    "zorro",

    # Nature
    "ambar", "arroyo", "aurora",
    "bambú", "bosque", "brisa",
    "cascada", "cedro", "cerro", "cipres", "colina", "coral",
    "cristal", "cumbre",
    "delta", "duna",
    "eclipse", "encina", "esmeralda", "estrella",
    "flor", "fuente",
    "glaciar", "granito",
    "horizonte",
    "isla",
    "jade", "jazmin",
    "lago", "lava", "lirio", "loto", "luna",
    "marea", "meseta", "monte", "musgo",
    "nube", "nogal",
    "oasis", "oceano", "olivo", "opalo", "orquidea",
    "palma", "pino", "pradera",
    "rayo", "rio", "roble", "rocio", "rosa", "rubi",
    "sauce", "selva", "sequoia", "sierra", "sol",
    "tormenta", "tulipan",
    "valle", "volcan",
    "zafiro",

    # Objects
    "ancla", "arco", "atlas",
    "bandera", "brujula",
    "campana", "castillo", "columna", "corona",
    "escudo", "espada", "estandarte", "estrella",
    "faro", "flauta", "forja", "fuente",
    "globo",
    "lanza", "linterna",
    "mapa", "martillo", "medalla", "molino", "mosaico",
    "oraculo",
    "palacio", "pergamino", "pilar", "portal", "prensa",
    "reloj", "runa",
    "senda", "templo", "torre", "tridente",
    "velero",

    # Authors / artists (born before 1900)
    "borges", "cervantes",
    "dario",
    "gaudi", "goya",
    "lorca", "machado", "marti", "neruda",
    "velazquez",

    # Fictional characters
    "dulcinea", "quixote", "sancho",
]
