# French word list for onionname suggestions (romanized ASCII)
# Format: adjective-noun (e.g., "joyeux-pingouin")
# People: only those born before 1900, no political/religious figures

ADJECTIVES = [
    "adroit", "agile", "aimable", "alerte", "amical", "ancien",
    "ardent", "astucieux", "attentif", "audacieux", "avise",
    "beau", "bienvenu", "bon", "brave", "brillant",
    "calme", "capable", "charmant", "cher", "clair", "clement",
    "content", "cordial", "courtois", "creatif", "curieux",
    "digne", "diligent", "discret", "doux", "droit", "durable",
    "elegant", "enchanté", "entier", "epique", "eternal",
    "fabuleux", "fertile", "festif", "fidele", "fin", "fluide",
    "fort", "frais", "franc", "fute",
    "gai", "galant", "genereux", "gentil", "glorieux", "gracieux",
    "grand", "gratuit",
    "habile", "hardi", "heureux", "honnete", "humble",
    "ideal", "illustre", "immense", "infini", "ingenieux",
    "joli", "jovial", "joyeux", "juste",
    "large", "leger", "libre", "limpide", "loyal", "lucide",
    "lumineux",
    "magique", "malin", "merveilleux", "modeste", "moral", "musical",
    "naturel", "net", "nimble", "noble", "nouveau",
    "ouvert", "optimal",
    "pacifique", "paisible", "parfait", "patient", "plaisant",
    "poli", "precieux", "precis", "premier", "propre", "prudent",
    "pur",
    "radieux", "rapide", "rare", "ravi", "remarquable", "resolut",
    "riche", "robuste", "royal", "rustique",
    "sacre", "sage", "savant", "serein", "simple", "sincere",
    "solide", "souple", "splendide", "stable", "subtil", "superbe",
    "sur",
    "tendre", "tenace", "timide", "total", "tranquille", "tropical",
    "unique", "utile",
    "vaillant", "valide", "vaste", "vibrant", "vif", "vivant",
    "zelé",
]

NOUNS = [
    # Animals
    "aigle", "albatros", "alouette", "antilope",
    "baleine", "belier", "biche", "bison", "blaireau",
    "canari", "castor", "cerf", "chamois", "chat", "cheval",
    "cigale", "cigogne", "colibri", "colombe", "condor", "cormoran",
    "coucou", "coyote", "cygne",
    "dauphin", "dingo",
    "ecureuil", "elan", "elephant", "emerillon",
    "faucon", "flamant", "fouine", "frelon",
    "gazelle", "girafe", "grue",
    "herisson", "heron", "hibou", "hirondelle",
    "jaguar",
    "kangourou", "koala",
    "leopard", "lievre", "lion", "loup", "loutre", "lynx",
    "manchot", "merle", "mesange", "moineau", "mouette",
    "narval",
    "oiseau", "orque", "ours",
    "panda", "panthere", "papillon", "pelican", "perdrix",
    "perroquet", "phoque", "pigeon", "pingouin", "pinson",
    "raton", "renard", "rossignol",
    "saumon", "scarabee", "serpent",
    "tigre", "tortue", "toucan", "truite",
    "vautour",
    "zebre",

    # Nature
    "aurore", "avalanche",
    "bambou", "basalte", "bouleau", "brume", "bruyere",
    "canyon", "cascade", "cedre", "cerise", "chataigne", "chene",
    "colline", "corail", "cristal", "cypres",
    "delta", "dune",
    "eclipse", "emeraude", "erable", "etang", "etoile",
    "falaise", "feuille", "fjord", "flamme", "fleur", "foret",
    "fontaine",
    "givre", "glacier", "granite",
    "horizon",
    "iris", "ivoire",
    "jade", "jasmin",
    "lac", "laurier", "lave", "lierre", "lotus",
    "marbre", "maree", "mousse", "montagne",
    "nuage",
    "oasis", "ocean", "olivier", "onyx", "opale", "orchidee",
    "palme", "peuplier", "pin", "platane", "prairie",
    "quartz",
    "ravin", "riviere", "roseau", "rubis",
    "sable", "safran", "sapin", "sauge", "sequoia", "source",
    "tempete", "tilleul", "tonnerre", "torrent", "tulipe",
    "vallee", "volcan",
    "zephyr",

    # Objects
    "ancre", "arc", "archive", "atlas",
    "balise", "banniere", "boussole", "brique",
    "cabane", "cadran", "chateau", "chemin", "clocher", "cloche",
    "colonne", "couronne",
    "dome", "drapeau",
    "ecrin", "embleme", "epee", "etendard",
    "fable", "flute", "forge", "forteresse",
    "globe", "gobelet",
    "harpe", "horloge",
    "icone",
    "javelin", "journal",
    "lanterne", "luth",
    "manoir", "marteau", "medaille", "miroir", "mosaique",
    "oracle",
    "palais", "parchemin", "pavillon", "phare", "pilier",
    "portail", "presse", "prisme", "puzzle",
    "quai",
    "rune",
    "sablier", "sceptre", "sentier", "signal",
    "talisman", "tapisserie", "temple", "torche", "tour",
    "trident",
    "voile", "voute",

    # Authors / artists / thinkers (born before 1900)
    "balzac", "baudelaire", "berlioz", "bizet",
    "cezanne", "chopin", "colette",
    "debussy", "degas", "delacroix", "dumas",
    "flaubert",
    "gauguin", "gautier",
    "hugo",
    "maupassant", "monet", "moliere", "montaigne",
    "pascal", "pasteur",
    "ravel", "renoir", "rodin", "ronsard", "rousseau",
    "satie",
    "verne", "voltaire",
    "zola",

    # Fictional characters
    "aramis", "artagnan", "asterix",
    "cyrano",
    "gavroche",
    "lancelot",
    "obelix",
    "porthos",
    "quixote",
    "valjean",
]
