# Japanese word list for onionname suggestions (romanized ASCII)
# Format: adjective-noun (e.g., "genki-tsuru")
# People: only those born before 1900, no political/religious figures

ADJECTIVES = [
    "akarui", "amai", "anshin", "atatakai", "azayaka",
    "chiisai", "chikai",
    "daitan", "doki",
    "erai",
    "fukahi", "fushigi", "futoi",
    "ganko", "genki",
    "hana", "hayai", "hiroi", "hokori", "honki",
    "iki", "inochi", "isamu",
    "jouzu", "junsei", "junsui",
    "kagayaku", "kanpeki", "karui", "kashikoi", "kawaii", "kaze",
    "keiken", "kenkou", "kirei", "kiyoi",
    "makoto", "manabi", "marui", "meicho", "mezurashi",
    "migoto", "minami", "moeru", "moroi", "mugen",
    "nagai", "nagoyaka", "narai", "nigiyaka", "noboru",
    "odayaka", "okii", "omoi", "origami",
    "raku", "reigai", "rikon", "rinri",
    "sabishi", "sakan", "sawayaka", "seijitsu", "senren",
    "shikaku", "shinpai", "shizuka", "shoujiki", "sugoi", "suteki",
    "tadashii", "takumi", "tanoshi", "tashika", "tuyoi",
    "ureshii", "uruwashi", "utukushi",
    "wakai", "warui", "watashi",
    "yasashii", "yasui", "yoi", "yosoi", "yutaka",
    "zen",
]

NOUNS = [
    # Animals
    "ahiru", "chidori",
    "hato", "hotaru",
    "inoshishi", "iruka",
    "kame", "karasu", "kiji", "kingyo", "kitsune", "koala",
    "koi", "kujira", "kumo", "kuma",
    "neko", "nezumi",
    "ookami", "oumu",
    "risu",
    "sagi", "sakana", "same", "shika", "suzume",
    "taka", "tancho", "tanuki", "tobimasu", "tora", "tsuru",
    "tsubame",
    "uma", "unagi", "usagi",
    "washi",
    "yamadori", "yama-neko",
    "zou",

    # Nature
    "ame", "arashi", "asahi",
    "botan",
    "fuji", "fuyu",
    "hana", "haru", "hayashi", "hikari", "hoshi",
    "inazuma", "iwa",
    "kawa", "kaze", "kiku", "kouyou", "kumo", "kusa",
    "mizu", "mori", "momo",
    "nami", "niji", "nishi",
    "oka",
    "rin",
    "sakura", "sango", "shima", "sora", "sugi",
    "taiyo", "take", "taki", "tani", "tsuchi", "tsuki",
    "umi",
    "yama", "yanagi", "yuki", "yuuhi",

    # Objects / concepts
    "budo",
    "chawan",
    "fue", "fude", "fusuma",
    "geta",
    "haiku", "hashi", "hikari",
    "ikebana",
    "kagami", "kago", "kasa", "katana", "koto",
    "makimono", "matsuri", "mon",
    "noren",
    "origami",
    "sensu", "shiro", "sumi", "suzu",
    "tatami", "torii", "tsurugi",
    "wa", "washi",
    "yumi",
    "zazen",

    # Authors / artists (born before 1900)
    "basho",
    "chikamatsu",
    "hiroshige", "hokusai",
    "kurosawa",
    "mishima", "murasaki",
    "sesshu", "soseki",
    "utamaro",
]
