# Dutch word list for onionname suggestions (romanized ASCII)
# Format: adjective-noun (e.g., "vrolijk-pinguïn")
# People: only those born before 1900, no political/religious figures

ADJECTIVES = [
    "actief", "aardig", "alert", "attent",
    "bedaard", "behendig", "bescheiden", "betrouwbaar", "blij",
    "braaf", "breed", "briljant",
    "charmant",
    "dapper", "degelijk", "dierbaar", "driftig", "durf",
    "edel", "eerlijk", "elegant", "enthousiast", "ernstig",
    "fier", "fijn", "flink", "flitsend", "fraai", "fris",
    "gastvrij", "geduldig", "gelukkig", "geschikt", "geweldig",
    "goedaardig", "gracieus", "grappig", "groot", "gulzig",
    "handig", "hartelijk", "helder", "hoopvol", "hulpvaardig",
    "ideaal", "ijverig",
    "jovial",
    "kalm", "keurig", "klaar", "knap", "kordaat", "krachtig",
    "kundig",
    "levendig", "lief", "loyaal", "lustig",
    "machtig", "mild", "moedig", "mooi", "munter",
    "netjes", "nobel", "nuttig",
    "open", "opgewekt", "oprecht",
    "pittig", "prachtig", "precies", "proper",
    "rank", "rap", "redelijk", "robuust", "rustig",
    "scherpzinnig", "simpel", "slim", "snel", "solide", "stevig",
    "stoer", "stralend",
    "trouw", "tuchtig",
    "uniek",
    "vaardig", "vast", "veilig", "verstandig", "vlot", "vrolijk",
    "vurig",
    "waard", "wakker", "warm", "wijs", "wonderlijk",
    "zacht", "zeker", "zonnig", "zuiver",
]

NOUNS = [
    # Animals
    "adelaar", "alk",
    "bever", "buizerd",
    "das", "dolfijn",
    "eekhoorn", "eend", "eland", "ekster",
    "fazant", "flamingo", "fuut",
    "gans", "gaai", "geit", "giraf",
    "haas", "havik", "hert", "hond",
    "ijsvogel",
    "kanarie", "kangoeroe", "kat", "koala", "kraanvogel", "kreeft",
    "leeuw", "leeuwerik", "lynx",
    "merel", "mees", "mol", "mus",
    "nachtegaal", "narwal",
    "ooievaar", "otter", "oehoe",
    "pauw", "pelikaan", "pinguïn", "pony",
    "raaf", "reiger", "ree", "roodborstje",
    "specht", "sperwer", "steur",
    "torenvalk", "tureluur",
    "uil",
    "valk", "vink", "vos", "vlinder",
    "walvis", "wolf", "wulp",
    "zalm", "zwaluw", "zwaan",

    # Nature
    "amber", "amethist",
    "basalt", "beek", "berg", "berk", "bloem", "bos", "branding",
    "cipres", "duin",
    "eik", "els", "esdoorn",
    "fjord", "gletsjer", "graniet",
    "haven", "heide", "heuvel", "horizon",
    "jade", "jasmijn",
    "klif", "koraal", "kristal",
    "linde", "lotus",
    "maan", "marmer", "meer", "mist", "mos",
    "oase", "oceaan", "opaal", "orchidee",
    "palm", "parel",
    "regenboog", "rivier", "robijn", "rots",
    "saffier", "sneeuw", "steen", "ster", "storm", "stroom",
    "tulp",
    "vallei", "vlam", "vulkaan",
    "waard", "weide", "wilg", "wind",
    "zephyr",

    # Objects
    "anker", "atlas",
    "baken", "banier", "brug", "burcht",
    "fakkel", "fluit",
    "globe", "gong",
    "hamer", "harp", "helm", "hoorn",
    "kandelaar", "kasteel", "klok", "kompas", "kroon",
    "lantaarn", "luit",
    "molen", "mozaïek",
    "orakel",
    "paleis", "pijler", "poort",
    "raadsel", "ridder", "rune",
    "schild", "spiegel", "spoor",
    "tempel", "toren",
    "vesting", "vuurtoren",
    "werkplaats",

    # Authors / artists / thinkers (born before 1900)
    "bosch", "brueghel",
    "erasmus", "escher",
    "hals",
    "mondriaan",
    "rembrandt",
    "spinoza",
    "vermeer", "vondel",
]
