# Portuguese (Brazilian) word list for onionname suggestions (romanized ASCII)
# Format: adjective-noun (e.g., "alegre-beija-flor")
# People: only those born before 1900, no political/religious figures

ADJECTIVES = [
    "abil", "agil", "alegre", "amavel", "amplo", "antigo",
    "ardente", "astuto", "atento", "audaz",
    "belo", "bondoso", "bravo", "brilhante",
    "calmo", "capaz", "caloroso", "claro", "cordial", "cortês",
    "criativo", "curioso",
    "decente", "diligente", "distinto", "doce", "duravel",
    "eficaz", "elegante", "encantado", "epico", "eterno",
    "fabuloso", "fertil", "festivo", "fiel", "fino", "firme",
    "fluido", "forte", "franco", "fresco",
    "galante", "generoso", "gentil", "glorioso", "gracioso",
    "grande", "grato",
    "habil", "honesto", "humilde",
    "ideal", "ilustre", "imenso", "infinito",
    "jovial", "justo", "juvenil",
    "leal", "leve", "livre", "lucido", "luminoso",
    "magico", "majestoso", "manso", "meigo", "modesto", "moral",
    "musical",
    "natural", "nobre", "notavel", "novo",
    "otimo", "ordenado",
    "pacifico", "paciente", "pleno", "preciso", "prudente", "puro",
    "querido", "quieto",
    "radioso", "rapido", "raro", "real", "resiliente", "rico",
    "robusto", "rustico",
    "sabio", "sagrado", "sereno", "simples", "sincero", "solar",
    "solido", "sublime", "suave", "sutil",
    "tenaz", "terno", "total", "tranquilo", "tropical",
    "unico", "util",
    "valente", "valioso", "vasto", "veloz", "vibrante", "vivido",
    "zeloso",
]

NOUNS = [
    # Animals
    "aguia", "anta", "arara",
    "baleia", "beija-flor", "borboleta", "bufalo",
    "camaleao", "canario", "capivara", "cardeal", "castor",
    "cigarra", "cisne", "coelho", "colibri", "condor", "coruja",
    "delfim",
    "elefante",
    "falcao", "flamingo", "foca",
    "garça", "gato", "girafa", "golfinho",
    "jaguar", "jacare",
    "leao", "leopardo", "lobo", "lontra",
    "macaco", "morcego",
    "onca", "orca",
    "panda", "papagaio", "pavao", "pelicano", "pinguim",
    "quetzal",
    "raposa", "rouxinol",
    "sabia", "salmao", "tartaruga", "tigre", "tucano",
    "urubu",
    "zebra",

    # Nature
    "ambar", "aurora",
    "bambu", "bosque", "brisa",
    "cachoeira", "canyon", "cedro", "cipeste", "colina", "coral",
    "cristal",
    "delta", "duna",
    "eclipse", "esmeralda", "estrela",
    "flor", "floresta", "fonte",
    "glaciar", "granito",
    "horizonte",
    "ilha",
    "jade", "jasmim",
    "lago", "lava", "lirio", "lotus", "lua",
    "mare", "montanha", "musgo",
    "nuvem",
    "oasis", "oceano", "opala", "orquidea",
    "palmeira", "pinheiro", "planicie", "praia",
    "quartzo",
    "raio", "rio", "rocha", "rosa", "rubi",
    "safira", "selva", "serra", "sol",
    "tempestade", "trovao", "tulipa",
    "vale", "vulcao",
    "zefiro",

    # Objects
    "ancora", "arco", "atlas",
    "bandeira", "bussola",
    "castelo", "coluna", "coroa",
    "escudo", "espada", "estandarte", "estrela",
    "farol", "flauta", "forja", "fortaleza",
    "globo",
    "harpa",
    "lanterna",
    "martelo", "medalha", "moinho", "mosaico",
    "oraculo",
    "palacio", "pergaminho", "pilar", "portal",
    "runa",
    "sino", "templo", "torre", "tridente",
    "veleiro",

    # Authors / artists (born before 1900)
    "camoes", "machado",
]
