# Chinese word list for onionname suggestions (romanized pinyin, ASCII)
# Format: adjective-noun (e.g., "kuaile-xiongmao")
# People: only those born before 1900, no political/religious figures

ADJECTIVES = [
    "anquan", "anran",
    "baogu", "bingxue",
    "caide", "changsheng", "chengshi", "chunzhen", "congming",
    "dafang", "dandan", "dingdang", "duoli",
    "fanghua", "feichang", "fenfu",
    "gangyi", "gaoxing", "gongzheng", "guangming", "guizhong",
    "haode", "haoqi", "hehe", "hongda", "huanle", "huoli",
    "jianchi", "jiankang", "jili", "jingcai", "jingque", "jiqiao",
    "kaifang", "kaixin", "kekao", "kuaile", "kuanrong",
    "langtian", "lianghao", "liangxin", "linghuo", "longzhong",
    "meili", "miaoman", "mingque", "minrui",
    "nenggan", "ningjing",
    "pingjing", "pushi",
    "qiangda", "qinfen", "qingxin", "quanli",
    "renai", "rexin", "rongguang", "ruanhe",
    "shanhe", "shanliang", "shenmi", "shuli",
    "tianzhen", "tongxin", "tuchu",
    "wanjian", "wenhe", "wenrou", "wunuan",
    "xianming", "xiaosa", "xingfu", "xiuya", "xuanli",
    "yonggan", "youhao", "youmei", "youxiu", "yuanqi", "yueshu",
    "zhencheng", "zhengyi", "zhihui", "zixin", "ziyou",
]

NOUNS = [
    # Animals
    "baihe", "bailu",
    "daxiang", "diao",
    "eyu",
    "fenghuang", "fuying",
    "gongji",
    "haigui", "haiou", "haitu", "hema", "heye", "houzi", "hudie",
    "jingyu", "jinsi",
    "konglongbird", "kongque",
    "langhua", "laoying", "longma", "luobo", "lüse",
    "mao", "meihualu",
    "niulang",
    "panda",
    "qilin", "qingting", "qingwa",
    "shanhu", "shanying", "shizi", "songhu", "songshu",
    "tanuki", "tianlang", "tuzi",
    "wugui",
    "xiongmao", "xique",
    "yanzi", "yingwu", "yuanyang", "yundou",
    "zhizhulang",

    # Nature
    "baihe", "baiyun",
    "chaoxia", "chunfeng",
    "dahai",
    "feixue", "fengye",
    "gushan",
    "haiyang", "heshan", "hongye", "huahai",
    "jianghe", "jingshi",
    "lanhua", "lianhua", "liushu",
    "meihua", "mingzhu", "moyu", "mudan",
    "nanfeng",
    "panshi", "pubu",
    "qingshan", "quanshui",
    "shanfeng", "shuijing", "songlin",
    "taiyang", "tianhe", "tushan",
    "wanxia",
    "xiagu", "xuehua", "xingchen",
    "yinhe", "yueguang", "yuehai", "yunhai",
    "zhulin",

    # Objects / concepts
    "baojian", "baoshan", "baota",
    "changcheng",
    "daoguang",
    "feibiao", "fengzheng",
    "gongdian", "guqin",
    "huabiao", "huoyan",
    "jianqiao", "jingshi",
    "lantern", "longchuan",
    "miaota",
    "qipan",
    "shanmen", "shufa", "sinan",
    "taiji", "taoqi", "tiandeng",
    "yupei",
    "zhonggu",

    # Poets / artists / thinkers (born before 1900)
    "baihua", "dufu",
    "libai", "liqingzhao",
    "sushi",
    "taoqian",
    "wangwei",
    "zhuangzi",
]
